[package]
name = "lolapi"
version = "0.1.0"
authors = ["SLeRest <sebastienlerest22@gmail.com>"]

[dependencies]
hyper = "0.12.28"
serde_json = "1.0.39"
hyper-tls = "0.3.2"
tokio = "0.1.19"
futures = "0.1.26"
